service:
  name: martelloneskill
app: martellone
org: sirlisko

plugins:
  - serverless-webpack
  - serverless-alexa-skills

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1

custom:
  alexa:
    # Step 1: Run `sls alexa auth` to authenticate
    # Step 2: Run `sls alexa create --name "Martellone Boris" --locale en-GB --type custom` to create a new skill
    skills:
      # Step 3: Paste the skill id returned by the create command here:
      # - id: amzn1.ask.skill.xxxx-xxxx-xxxx-xxxx-xxxx
        manifest:
          publishingInformation:
            category: NOVELTY
            isAvailableWorldwide: true
            distributionMode: PUBLIC
            testingInstructions: Nothing specifical, it just plays an audio
            locales:
              en-GB:
                name: Martellone Boris
                description: If you watched Boris (Italian TV Shows) you know what this is about :)
                examplePhrases:
                  - Alexa, ask Martellone what does he think about it
                keywords:
                  - boris
                  - martellone
                  - sticazzi
                summary: Ask Boris' Martellone what does he think about stuff. He will reply with his most famous punch line.
                smallIconUri: https://github.com/sirLisko/martellone-alexa-skill/raw/master/icons/martellone-icon-small.png
                largeIconUri: https://github.com/sirLisko/martellone-alexa-skill/raw/master/icons/martellone-icon.png
              it-IT:
                name: Martellone Boris
                description: Skill pensata per tutti gli amanti di Nando Martellone, interpretato dal mitico Massimiliano Bruno, nella serie TV Boris.
                examplePhrases:
                  - Alexa, domanda a Nando Martellone cosa ne pensa
                keywords:
                  - boris
                  - martellone
                  - sticazzi
                summary: Chiedi a Martellone cosa ne pensa, ti risponderà cosa la sua più tipica delle espressioni
                smallIconUri: https://github.com/sirLisko/martellone-alexa-skill/raw/master/icons/martellone-icon-small.png
                largeIconUri: https://github.com/sirLisko/martellone-alexa-skill/raw/master/icons/martellone-icon.png
          privacyAndCompliance:
            allowsPurchases: false
            usesPersonalInfo: false
            isChildDirected: false
            isExportCompliant: true
            containsAds: false
          apis:
            custom:
              endpoint:
                # Step 4: Do your first deploy of your Serverless stack
                # Step 5: Paste the ARN of your lambda here:
                # uri: arn:aws:lambda:[region]:[account-id]:function:[function-name]
                # Step 6: Run `sls alexa update` to deploy the skill manifest
                # Step 7: Run `sls alexa build` to build the skill interaction model
                # Step 8: Enable the skill in the Alexa app to start testing.
          manifestVersion: "1.0"
        models:
          en-GB:
            interactionModel:
              languageModel:
                invocationName: martellone what
                intents:
                  - name: StiCazziIntent
                    samples:
                      - do you think about this
                      - do you think about it
                      - does he think about this
                      - does he think about it
                      - do you think
                      - does he think
                      - you think
                      - is his opinion
                  - name: AMAZON.StopIntent
          it-IT:
            interactionModel:
              languageModel:
                invocationName: nando martellone
                intents:
                  - name: StiCazziIntent
                    samples:
                      - un parere
                      - un pensiero
                      - un'opinione
                      - un commento
                      - cosa ne pensi di questa cosa
                      - cosa ne pensi di questo
                      - cosa ne pensi
                      - cosa ne pensa di questa cosa
                      - cosa ne pensa
                  - name: AMAZON.StopIntent

functions:
  alexa:
    handler: handler.alexa
    events:
      - alexaSkill: ${self:custom.alexa.skills.0.id}
